server:
  port: 18080

spring:
  application:
    name: onethread-nacos-cloud-example
  config:
    import: optional:nacos:onethread-nacos-cloud-example.yaml
  profiles:
    active: dev

  cloud:
    nacos:
      config:
        server-addr: 117.72.33.162:8848
        file-extension: yaml
        extension-configs:
          - data-id: onethread-nacos-cloud-example.yaml
            group: DEFAULT_GROUP
            refresh: true
