# 在 Nacos 创建 data-id 为 {onethread.nacos.data-id} 和 {onethread.nacos.group} 的配置文件
# 并将下述配置复制到该文件中
onethread:
  nacos:
    data-id: onethread-nacos-cloud-example.yaml
    group: DEFAULT_GROUP
  config-file-type: yaml
  executors:
    - thread-pool-id: onethread-producer
      core-pool-size: 12
      maximum-pool-size: 24
      keep-alive-time: 19999
      work-queue: ResizableCapacityLinkedBlockingQueue
      queue-capacity: 10000
      rejected-handler: CallerRunsPolicy
      allow-core-thread-time-out: false
    - thread-pool-id: onethread-consumer
      core-pool-size: 10
      maximum-pool-size: 20
      keep-alive-time: 9999
      work-queue: LinkedBlockingQueue
      queue-capacity: 1024
      rejected-handler: AbortPolicy
      allow-core-thread-time-out: true
